import { api } from './api/apps-script-api.js';import { byId, setSaveState, showToast } from './shared/dom.js';import { store } from './shared/store.js';import { renderEditor } from './editor/block-editor.js';import { scheduleSave, saveNow } from './editor/autosave.js';import { renderPreview, changeZoom, fitPreview, printPdf } from './preview/preview-renderer.js';import { openLibrary, closeLibrary, loadLibrary } from './library/library-drawer.js';import { initializeSaveEvents } from './editor/save-events.js';
store.subscribe(()=>{renderEditor();renderPreview()});
byId('new-book').addEventListener('click',()=>byId('new-book-dialog').showModal());
byId('new-book-form').addEventListener('submit',async event=>{event.preventDefault();try{const book=await api.createBook({name:byId('new-book-name').value,sourceLanguage:byId('new-source').value,targetLanguage:byId('new-target').value});byId('new-book-dialog').close();loadBook(book)}catch(error){showToast(error.message)}});
byId('open-library').addEventListener('click',openLibrary);byId('close-library').addEventListener('click',closeLibrary);byId('library-search').addEventListener('input',loadLibrary);byId('save-now').addEventListener('click',saveNow);byId('zoom-out').addEventListener('click',()=>changeZoom(-.08));byId('zoom-in').addEventListener('click',()=>changeZoom(.08));byId('fit-preview').addEventListener('click',fitPreview);byId('download-pdf').addEventListener('click',printPdf);
document.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>{store.addBlock(button.dataset.add);scheduleSave()}));
['book-name','source-language','target-language','book-status'].forEach(id=>byId(id).addEventListener('input',()=>{const state=store.getState();if(!state.book)return;state.book.name=byId('book-name').value;state.book.sourceLanguage=byId('source-language').value;state.book.targetLanguage=byId('target-language').value;state.book.status=byId('book-status').value;store.markBookChanged();store.notify();scheduleSave()}));
document.addEventListener('book:open',async event=>{try{loadBook(await api.getBook(event.detail));closeLibrary()}catch(error){showToast(error.message)}});
document.addEventListener('paste',event=>{const file=[...event.clipboardData.items].find(item=>item.type.startsWith('image/'))?.getAsFile();if(!file)return;let block=store.getState().blocks.find(item=>item.type==='imagem'&&!item.imageFileId);if(!block){store.addBlock('imagem');block=store.getState().blocks.at(-1)}document.dispatchEvent(new CustomEvent('image:paste',{detail:{blockId:block.blockId,file}}))});
document.addEventListener('image:paste',async event=>{const {uploadImage}=await import('./editor/image-upload.js');uploadImage(event.detail.blockId,event.detail.file)});
initializeSaveEvents(document.querySelector('.editor-panel'));
function loadBook(book){store.setBook(book);byId('book-name').value=book.name||'';byId('source-language').value=book.sourceLanguage||'en';byId('target-language').value=book.targetLanguage||'pt';byId('book-status').value=book.status||'Em andamento';byId('current-book').textContent=book.name;setSaveState('Pronto')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');renderEditor();renderPreview();
